### ISSUE TITLE
Add info/FAQ

### ISSUE THREAD

**Issue by filoxo** [filoxo/key-tester#5]
Maybe just a single line at the bottom of the page? Or something more informative?

**Comment by nayonnapurnell** [comment]
Are you looking for an info/FAQ page?  Your project is my first open source project.  I can add a FAQ line but at the bottom of what page?

**Comment by filoxo** [comment]
My idea for this is just to have a simple "made with" message, or maybe just a boring copyright at the bottom of the page. 

We likely won't use this webcomponent but here's an example thing that I've seen on a few sites, just to give you an idea.
https://studiopress.blog/made-with-love-footer/
https://github.com/nitayneeman/made-with-love

I was also thinking that that would be a good place for a button that opens an FAQ, most likely within a modal. The only content that comes to mind for something like that would be: explain the limitations of this tester, links to external projects, maybe some other stuff. This isn't well defined so we may not add this until it becomes necessary
